// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/aarathyaadhiv/fashionstore-product-service/pkg/api"
	"github.com/aarathyaadhiv/fashionstore-product-service/pkg/api/service"
	"github.com/aarathyaadhiv/fashionstore-product-service/pkg/config"
	"github.com/aarathyaadhiv/fashionstore-product-service/pkg/db"
	"github.com/aarathyaadhiv/fashionstore-product-service/pkg/repository"
)

// Injectors from wire.go:

func InitializeAPI(c config.Config) (*api.ServerHTTP, error) {
	gormDB, err := db.ConnectDatabase(c)
	if err != nil {
		return nil, err
	}
	productRepository := repository.NewProductRepository(gormDB)
	productService := service.NewProductService(productRepository)
	serverHTTP := api.NewServerHTTP(productService)
	return serverHTTP, nil
}
