// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/aarathyaadhiv/fashionstore-user-service/pkg/api"
	"github.com/aarathyaadhiv/fashionstore-user-service/pkg/api/service"
	"github.com/aarathyaadhiv/fashionstore-user-service/pkg/config"
	"github.com/aarathyaadhiv/fashionstore-user-service/pkg/db"
	"github.com/aarathyaadhiv/fashionstore-user-service/pkg/repository"
)

// Injectors from wire.go:

func InitializeAPI(c config.Config) (*api.ServerHTTP, error) {
	gormDB, err := db.ConnectDatabse(c)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(gormDB)
	userService := service.NewUserService(userRepository)
	serverHTTP := api.NewServerHTTP(userService)
	return serverHTTP, nil
}
