// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/aarathyaadhiv/fashionstore-cart-service/pkg/api"
	"github.com/aarathyaadhiv/fashionstore-cart-service/pkg/api/service"
	"github.com/aarathyaadhiv/fashionstore-cart-service/pkg/client"
	"github.com/aarathyaadhiv/fashionstore-cart-service/pkg/config"
	"github.com/aarathyaadhiv/fashionstore-cart-service/pkg/db"
	"github.com/aarathyaadhiv/fashionstore-cart-service/pkg/repository"
)

// Injectors from wire.go:

func InitializeAPI(c config.Config) (*api.ServerHTTP, error) {
	gormDB, err := db.ConnectDatabase(c)
	if err != nil {
		return nil, err
	}
	cartRepository := repository.NewCartRepository(gormDB)
	productClient := client.NewProductClient(c)
	cartService := service.NewCartService(cartRepository, productClient)
	serverHTTP := api.NewServerHTTP(cartService)
	return serverHTTP, nil
}
