// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/aarathyaadhiv/fashionstore-admin-service/pkg/api"
	"github.com/aarathyaadhiv/fashionstore-admin-service/pkg/api/service"
	"github.com/aarathyaadhiv/fashionstore-admin-service/pkg/config"
	"github.com/aarathyaadhiv/fashionstore-admin-service/pkg/db"
	"github.com/aarathyaadhiv/fashionstore-admin-service/pkg/repository"
)

// Injectors from wire.go:

func InitializeAPI(c config.Config) (*api.ServerHTTP, error) {
	gormDB, err := db.ConnectDatabase(c)
	if err != nil {
		return nil, err
	}
	adminRepository := repository.NewAdminRepository(gormDB)
	adminService := service.NewAdminService(adminRepository)
	serverHTTP := api.NewServerHTTP(adminService)
	return serverHTTP, nil
}
